variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - test

asm:
  stage: build
  script:
    - make asm
  only:
    - master
    - dev

cw:
  stage: build
  script:
    - make corewar
  only:
    - master
    - dev

fuzz_asm:
  stage: test
  script:
    - cd test && python3 cw_fuzzer.py -m asm
  artifacts:
    paths:
      - test/traces
    expire_in: 1 week
  only:
    - master
    - dev
    - test

fuzz_cw:
  stage: test
  script:
    - cd test && python3 cw_fuzzer.py -m corewar
  only:
    - master
    - dev
