variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - test
  - build

asm:
  script:
    - make asm
  only:
    - dev
    - master

cw:
  script:
    - make corewar
  only:
    - dev
    - master

test:
  stage: test
  script:
    - sh test/run.sh
  only:
    - dev
    - master