variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - test

asm:
  stage: build
  script:
    - make asm
  only:
    - master
    - dev

cw:
  stage: build
  script:
    - make corewar
  only:
    - master
    - dev

fuzz_asm:
  stage: test
  script:
    - python3 test/cw_fuzzer.py -m asm -db test/db.pcl
  only:
    - master
    - dev
    - test

fuzz_cw:
  stage: test
  script:
    - python3 test/cw_fuzzer.py -m corewar -db test/db.pcl
  only:
    - master
    - dev
